# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1 ,2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int32'), 12, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [51]:
# Create an array of shape (10, 2) with only ones
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [48]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10, size=(7, 2))

array([[8, 0],
       [9, 2],
       [6, 3],
       [8, 2],
       [4, 2],
       [6, 4],
       [8, 6]])

In [49]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size = (3,5))

array([[0.01326496, 0.94220176, 0.56328822, 0.3854165 , 0.01596625],
       [0.23089383, 0.24102547, 0.68326352, 0.60999666, 0.83319491],
       [0.17336465, 0.39106061, 0.18223609, 0.75536141, 0.42515587]])

In [47]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [40]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
uniquo = np.random.randint(10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(uniquo)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [42]:
uniquo

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6],
       [1, 3, 8, 1, 9, 8, 9]])

In [41]:
# Find the 0'th index of the latest array you created
uniquo[0]

array([8, 0, 9, 2, 6, 3, 8])

In [44]:
# Get the first 2 rows of latest array you created
uniquo[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [46]:
# Get the first 2 values of the first 2 rows of the latest array
uniquo[:2, :2]

array([[8, 0],
       [2, 4]])

In [67]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand1 = np.random.randint(10, size=(3, 5))
ones = np.ones((3, 5))
rand1 , ones

(array([[6, 8, 9, 9, 2],
        [6, 0, 3, 3, 4],
        [6, 6, 3, 6, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [68]:
# Add the two arrays together
rand1 + ones

array([[ 7.,  9., 10., 10.,  3.],
       [ 7.,  1.,  4.,  4.,  5.],
       [ 7.,  7.,  4.,  7.,  3.]])

In [69]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))

In [70]:
# Try add the array of ones and the other most recent array together
rand1 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [71]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
# Subtract the new array of ones from the other most recent array
rand1 - ones

array([[ 5.,  7.,  8.,  8.,  1.],
       [ 5., -1.,  2.,  2.,  3.],
       [ 5.,  5.,  2.,  5.,  1.]])

In [74]:
# Multiply the ones array with the latest array
rand1 * ones

array([[6., 8., 9., 9., 2.],
       [6., 0., 3., 3., 4.],
       [6., 6., 3., 6., 2.]])

In [75]:
# Take the latest array to the power of 2 using '**'
rand1 ** 2

array([[36, 64, 81, 81,  4],
       [36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4]])

In [76]:
# Do the same thing with np.square()
np.square(rand1)

array([[36, 64, 81, 81,  4],
       [36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4]])

In [77]:
# Find the mean of the latest array using np.mean()
np.mean(rand1)

4.866666666666666

In [78]:
# Find the maximum of the latest array using np.max()
np.max(rand1)

9

In [79]:
# Find the minimum of the latest array using np.min()
np.min(rand1)

0

In [83]:
# Find the standard deviation of the latest array
np.std(rand1)

2.604269997949948

In [81]:
# Find the variance of the latest array
np.var(rand1)

6.782222222222223

In [84]:
# Reshape the latest array to (3, 5, 1)
rand1.reshape(3, 5, 1)

array([[[6],
        [8],
        [9],
        [9],
        [2]],

       [[6],
        [0],
        [3],
        [3],
        [4]],

       [[6],
        [6],
        [3],
        [6],
        [2]]])

In [85]:
# Transpose the latest array
rand1.T

array([[6, 6, 6],
       [8, 0, 6],
       [9, 3, 3],
       [9, 3, 6],
       [2, 4, 2]])

What does the transpose do?

In [86]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

rand2 = np.random.randint(10, size=(3, 3))
rand3 = np.random.randint(10, size=(3, 2))
rand2, rand3

(array([[5, 1, 9],
        [8, 4, 5],
        [3, 9, 6]]),
 array([[8, 6],
        [0, 0],
        [8, 8]]))

In [87]:
# Perform a dot product on the two newest arrays you created
rand2.dot(rand3)

array([[112, 102],
       [104,  88],
       [ 72,  66]])

In [88]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand4 = np.random.randint(10, size=(4, 3))
rand5 = np.random.randint(10, size=(4, 3))
rand4, rand5

(array([[3, 8, 2],
        [6, 5, 7],
        [8, 4, 0],
        [2, 9, 7]]),
 array([[5, 7, 8],
        [3, 0, 0],
        [9, 3, 6],
        [1, 2, 0]]))

In [89]:
# Perform a dot product on the two newest arrays you created
rand4.dot(rand5)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [90]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand4.dot(rand5.T)

array([[ 87,   9,  63,  19],
       [121,  18, 111,  16],
       [ 68,  24,  84,  16],
       [129,   6,  87,  20]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [105]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand6 = np.random.randint(10, size=(2, 3))
rand7 = np.random.randint(10, size=(2, 3))
rand6, rand7

(array([[6, 4, 0],
        [0, 2, 1]]),
 array([[4, 9, 5],
        [6, 3, 6]]))

In [106]:
# Compare the two arrays with '>'
rand6 > rand7

array([[ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [107]:
# Compare the two arrays with '>='
rand6 >= rand7

array([[ True, False, False],
       [False, False, False]])

In [108]:
# Find which elements of the first array are greater than 7
rand6 > 7

array([[False, False, False],
       [False, False, False]])

In [109]:
# Which parts of each array are equal? (try using '==')
rand6 == rand7

array([[False, False, False],
       [False, False, False]])

In [110]:
# Sort one of the arrays you just created in ascending order
rand6.sort()
rand6

array([[0, 4, 6],
       [0, 1, 2]])

In [114]:
# Sort the indexes of one of the arrays you just created
rand7.argsort()

array([[0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [115]:
# Find the index with the maximum value in one of the arrays you've created
rand6.argmax()

2

In [116]:
# Find the index with the minimum value in one of the arrays you've created
rand7.argmin()

4

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
rand7.argmin(axis=1)

array([0, 1], dtype=int64)

In [118]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
rand7.argmin(axis=0)

array([0, 1, 0], dtype=int64)

In [119]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.77533611,  0.77314086, -0.80182784,  1.38401572,  1.40520531],
       [ 1.39232575, -0.88064082,  0.07689495, -0.49343248,  0.92316261],
       [ 1.70660495,  0.87358942,  0.00914435, -0.3655393 ,  0.64908673]])

In [120]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.